### ISSUE TITLE
PrintTableMetricsCallback does not handle metrics with periods

### ISSUE THREAD

**Issue by anaoum** [Lightning-AI/lightning-bolts#955]
## 🐛 Bug

When logged metrics have a period, the PrintTableMetricsCallback produces a KeyError.

#### Code sample

```python
from pl_bolts.callbacks.printing import dicts_to_table

print(dicts_to_table([{"metrics/class.a": 0.5}]))
```

### Expected behavior

```
metrics/class.a
---------------
0.5
```

### Actual behavior
```
Traceback (most recent call last):
  File "/home/coder/temp.py", line 3, in <module>
    dicts_to_table([{"metrics/class.a": 0.5}])
  File "/home/coder/.direnv/python-3.8.10/lib/python3.8/site-packages/pl_bolts/utils/stability.py", line 87, in wrapper
    return cls_or_callable(*args, **kwargs)
  File "/home/coder/.direnv/python-3.8.10/lib/python3.8/site-packages/pl_bolts/callbacks/printing.py", line 129, in dicts_to_table
    line = s.format(**d, **marked_values)
KeyError: 'metrics/class'
```

### Environment

- PyTorch Version (e.g., 1.0): 1.12.1+cu116
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): N/A
- Python version: 3.8
- CUDA/cuDNN version: 11.6
- GPU models and configuration: N/A
- Any other relevant information: N/A

### Additional context

The underlying problem is [here](https://github.com/Lightning-AI/lightning-bolts/blob/master/pl_bolts/callbacks/printing.py#L129), python format strings cannot have a period in variable names. To reproduce underlying issue:
```python
"{metrics/class.a}".format(**{"metrics/class.a": 0.5})
```

**Comment by Borda** [comment]
@anaoum, would you be interested in sending a fix? :)
