### ISSUE TITLE
lightning-bolts is referring to LightningLoggerBase from pytorch-lightning but this has been renamed a year ago

### ISSUE THREAD

**Issue by deepio-oc** [Lightning-AI/lightning-bolts#983]
## 🐛 Bug

Rename from LightningLoggerBase to Logger was done here:

https://github.com/Lightning-AI/lightning/issues/11971

### To Reproduce

from pl_bolts.datamodules import MNISTDataModule

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/conda/lib/python3.10/site-packages/pl_bolts/__init__.py", line 11, in <module>
    from pl_bolts import (  # noqa: E402
  File "/usr/conda/lib/python3.10/site-packages/pl_bolts/callbacks/__init__.py", line 3, in <module>
    from pl_bolts.callbacks.data_monitor import ModuleDataMonitor, TrainingDataMonitor
  File "/usr/conda/lib/python3.10/site-packages/pl_bolts/callbacks/data_monitor.py", line 6, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase, TensorBoardLogger, WandbLogger
ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/usr/conda/lib/python3.10/site-packages/pytorch_lightning/loggers/__init__.py)
```

#### Code sample

from pl_bolts.datamodules import MNISTDataModule

### Expected behavior

MNISTDataModule should be imported without error

### Environment

- PyTorch Version: pytorch-lightning==1.9.3
- OS: linux
- How you installed PyTorch: pytorch-lightning==1.9.3
- Python version: 3.10

**Comment by deepio-oc** [comment]
duplicate of https://github.com/Lightning-AI/lightning-bolts/issues/962
